### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fidley** [stockbal/abap-search-tools-ui#1]
Hi @stockbal , 

I have problem with installation. I know it comes from the proxy and SSL handshake. It appears when you deploy your plugin to website that uses HTTPS protocol. I had the same issue with ABAP Favorites when I've added the SSL certificate for website. 

I know the solution is to add github certificate to the Java certificate storage, but sometimes, especially in corporate world, you don't have sufficient authorizations to do so. So in case of my plugin, I've moved this to HTTP protocol.
![image](https://user-images.githubusercontent.com/7912195/69032747-83178300-09dd-11ea-970e-2556cce4f58e.png)

**Comment by stockbal** [comment]
Hi @fidley,

maybe you can try the solution with the windows system environment variables. Add the following line to the system environment variables:
`JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStoreType=Windows-ROOT`.   
If this does not work, do you think it will be enough if I just replace the `https` with `http` in my github updatesite path?. I tried it just now in my eclipse installation and the plugins from the site were loaded fine. 

Maybe you can try both approaches give me some feedback afterwards

Regards
Ludwig

**Comment by fidley** [comment]
@stockbal setting of user variable in the system helped. The option with changing HTTPS to HTTP don't change anything. I guess there is redirection to HTTPS anyway :)
